Fixed unit tests and CI. (#192)

diff --git a/.github/workflows/onmergerelease.yml b/.github/workflows/onmergerelease.yml
--- a/.github/workflows/onmergerelease.yml
+++ b/.github/workflows/onmergerelease.yml
@@ -34,3 +34,7 @@ jobs:
       - name: Unit Test Coverage
         run: |
           make test-coverage
+          if [ $? -ne 0 ]; then
+            echo "Unit tests failed"
+            exit 1
+          fi
