Added workflow for security file check (#156)

diff --git a/.github/workflows/onpullrequest.yml b/.github/workflows/onpullrequest.yml
--- a/.github/workflows/onpullrequest.yml
+++ b/.github/workflows/onpullrequest.yml
@@ -6,13 +6,26 @@ on:
 permissions: read-all
 
 jobs:
-  version-check:
+
+  security-file-check:
     runs-on: [ ubuntu-20.04 ]
     steps:
-      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
+      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
         with:
           fetch-depth: 0
-      
+
+      - name: Check Security.md file
+        run: |
+          if [ ! -f ./Security.md ]; then
+            echo "Security.md file is missing"
+            exit 1
+          fi
+
+  version-check:
+    runs-on: [ ubuntu-20.04 ]
+    needs: [ "security-file-check" ]
+    steps:
+
       - name: version-check
         run: |
           /bin/bash version-check.sh
@@ -28,9 +41,6 @@ jobs:
       https_proxy: ${{ secrets.HTTPS_PROXY }}
       no_proxy: ${{ secrets.NO_PROXY }}
     steps:
-      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
-        with:
-          fetch-depth: 0
 
       - name: Setup Go
         uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
